# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/BE_jjalseu_playground
            git pull origin main
            ./gradlew build -x test
            sudo pkill -f 'java -jar /home/ubuntu/BE_jjalseu_playground/build/libs/BE_playground-0.0.1-SNAPSHOT.jar'
            nohup java -jar /home/ubuntu/BE_jjalseu_playground/build/libs/BE_playground-0.0.1-SNAPSHOT.jar > /home/ubuntu/myapp.log 2>&1 &
            disown 
            sleep 10  
            sudo systemctl restart nginx  
