## .github/workflows/deploy.yml
#name: Deploy to EC2
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    timeout-minutes: 20
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Deploy to EC2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USER }}
#          key: ${{ secrets.EC2_KEY }}
#          port: 22
#          timeout: 30m
#          script: |
#            cd /home/ubuntu/BE_jjalseu_playground
#            git pull origin main
#            ./gradlew build -x test
#            nohup java -jar /home/ubuntu/BE_jjalseu_playground/build/libs/BE_playground-0.0.1-SNAPSHOT.jar &
#            sudo systemctl restart nginx
