name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 배포 진행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add PEM key
        run: |
          echo "${{ secrets.EC2_KEY }}" > enjoyjjalseu.pem
          chmod 400 enjoyjjalseu.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i enjoyjjalseu.pem -r ./build/libs/*.jar ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/app/

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i enjoyjjalseu.pem ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/app
          pkill -f 'java -jar' || true
          nohup java -jar *.jar > /dev/null 2>&1 &
          EOF
