name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 배포 진행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add PEM key
        run: |
          echo "${{ secrets.EC2_KEY }}" > enjoyjjalseu.pem
          chmod 400 enjoyjjalseu.pem

      - name: Copy source code to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i enjoyjjalseu.pem -r * ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/app/


      - name: Build and deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i enjoyjjalseu.pem ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/app
          ./gradlew build -x test  # Gradle 빌드 실행
          pkill -f 'java -jar' || true  # 기존 애플리케이션 종료
          nohup java -jar build/libs/BE_playground-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &
          EOF

      - name: Check if application is running
        run: |
          ssh -o StrictHostKeyChecking=no -i enjoyjjalseu.pem ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com << 'EOF'
          ps -ef | grep java
          tail -n 20 /home/ubuntu/app/nohup.out
          EOF

      - name: Check 8080 port
        run: |
          ssh -T -o StrictHostKeyChecking=no -i enjoyjjalseu.pem ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com "sudo ss -tuln | grep 8080"

