name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 배포 진행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Add PEM key
        run: |
          echo "${{ secrets.EC2_KEY }}" > enjoyjjalseu.pem
          chmod 400 enjoyjjalseu.pem

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i enjoyjjalseu.pem ./build/libs/BE_playground-0.0.1-SNAPSHOT.jar ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/app/


      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i enjoyjjalseu.pem ubuntu@ec2-3-39-228-240.ap-northeast-2.compute.amazonaws.com << 'EOF'
          cd /home/ubuntu/app
          pkill -f 'java -jar' || true
          nohup java -jar BE_playground-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
          EOF
